name: tes_project
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  firebase_auth: ^4.12.0  # Sesuaikan versi sesuai kebutuhan Anda
  cloud_firestore: ^4.12.0
  avatar_view: ^1.0.1
  firebase_core: ^2.8.1     # Sesuaikan versi sesuai kebutuhan Anda
  fluttertoast: ^8.2.2
  firebase_core_web: ^2.8.1
  firebase_auth_web: ^5.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/